### ISSUE TITLE
MaxPoolGrad already registered in tensorflow 1.2

### ISSUE THREAD

**Issue by winston-zillow** [cbfinn/maml#12]
Got the error below. Current work around is to comment out the ```special_grads.py```

```
(tf2) ~/3rdparty/maml$ pip3 list | grep tensorflow
tensorflow (1.2.1)

(tf2) ~/3rdparty/maml$ python3 main.py --train=False --datasource=miniimagenet --metatrain_iterations=60000 --meta_batch_size=4 --update_batch_size=5 --update_lr=0.01 --num_updates=5 --num_classes=5 --logdir=logs/miniimagenet5shot/ --num_filters=32 --max_pool=True --stop_grad=True
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    from maml import MAML
  File "/Users/winstonq/3rdparty/maml/maml.py", line 3, in <module>
    import special_grads
  File "/Users/winstonq/3rdparty/maml/special_grads.py", line 6, in <module>
    @ops.RegisterGradient("MaxPoolGrad")
  File "/Users/winstonq/.tox/tf2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1750, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/Users/winstonq/.tox/tf2/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'MaxPoolGrad' !(Previous registration was in _find_and_load_unlocked <frozen importlib._bootstrap>:958)"
```

**Comment by cbfinn** [comment]
Yes. I think the best workaround for now is to comment out the import to special grads, since there might be people still using TF v1.0 and v1.1. Feel free to make a PR to comment out the import and add a comment to uncomment the import if using a version of TF without MaxPoolGradGrad implemented.

**Comment by cbfinn** [comment]
Resolved in https://github.com/cbfinn/maml/pull/13
