### ISSUE TITLE
Exception running Omniglot 20-way 5-shot

### ISSUE THREAD

**Issue by unixpickle** [cbfinn/maml#22]
When I run 20-way 1-shot like so, everything works fine:

```
sh-log FOML-O520 python main.py --datasource=omniglot --metatrain_iterations=40000 --meta_batch_size=16 --update_batch_size=1 --num_classes=20 --update_lr=0.1 --num_updates=5 --logdir=logs/omniglot20way/ --stop_grad=True
```

However, when I change `--update_batch_size` to 5, I see this error:

```
Generating filenames
Traceback (most recent call last):
  File "main.py", line 346, in <module>
    main()
  File "main.py", line 267, in main
    image_tensor, label_tensor = data_generator.make_data_tensor()
  File "/root/code/maml/data_generator.py", line 104, in make_data_tensor
    filename_queue = tf.train.string_input_producer(tf.convert_to_tensor(all_filenames), shuffle=False)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 932, in convert_to_tensor
    as_ref=False)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 233, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 218, in constant
    name=name).outputs[0]
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1569, in __init__
    "Cannot create a tensor proto whose content is larger than 2GB.")
ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```

This is with `tensorflow-gpu` version 1.5.0. Any pointers would be great!

**Comment by unixpickle** [comment]
Oh, silly me. I missed issue #3.
